# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 07:50
from __future__ import unicode_literals

import database.my_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='volunteerList',
            field=database.my_field.ListField(default=[]),
        ),
    ]
