# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 14:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_teacher_volunteerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='realName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='(\\d|\\w){4,}')]),
        ),
    ]
