# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 16:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20161005_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\d|\\w){4,}$')]),
        ),
    ]
