# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 02:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20161006_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='12345678', max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\d|\\w){4,}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(regex='^(\\d)+$')]),
        ),
    ]
