# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
