# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20161012_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
