# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20161012_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ID',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
