# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20161012_1358'),
        ('database', '0011_auto_20161012_0023'),
    ]

    operations = [
    ]
