# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
