# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_registercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='exam_picture/None/no-img.jpg', upload_to='exam_picture/')),
            ],
        ),
    ]
