# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20161017_2343'),
        ('database', '0017_auto_20161018_1124'),
    ]

    operations = [
    ]
