# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20161018_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='account',
            field=models.CharField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
