# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20161019_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fixedPhone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='wechat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fixedPhone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wechat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='fixedPhone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='wechat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
