# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20161019_2100'),
        ('database', '0018_merge'),
    ]

    operations = [
    ]
