# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_teacher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
