# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20161020_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(default='student/static/images/None/no-img.jpg', upload_to='student/static/images'),
        ),
    ]
