# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20161023_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='account',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='img',
        ),
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='province',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='subject',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='admissionStatus',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='admissionStatus',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
