# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20161026_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='isDelivered',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='isTitle',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='estimateScore',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
