# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20161026_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='estimateScore',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
