# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20161026_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_list', models.CharField(blank=True, default='', max_length=500)),
                ('stu_list', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(blank=True, default='', max_length=300)),
                ('receive_vol', models.CharField(blank=True, default='', max_length=500)),
                ('receive_stu', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
