# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_group_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
