# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20161029_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duiyingTeacher',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
