# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_student_duiyingteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('start_time', models.CharField(blank=True, default='', max_length=100)),
                ('end_time', models.CharField(blank=True, default='', max_length=100)),
                ('volunteer_dic', models.CharField(blank=True, default='{}', max_length=1000)),
            ],
        ),
    ]
