# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='estimateScore',
            field=models.CharField(blank=True, default='{}', max_length=2000),
        ),
    ]
