# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20161031_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_time',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
