# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20161101_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='stu_list',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='group',
            name='vol_list',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
