# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20161101_2228'),
        ('database', '0038_auto_20161102_1358'),
    ]

    operations = [
    ]
