# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(blank=True, default='{}', max_length=1000)),
                ('message_url', models.CharField(blank=True, default='{}', max_length=1000)),
            ],
        ),
    ]
