# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_wechaturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quanxian',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='quanxian',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
