# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20161103_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='estimateScore',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
