# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 15:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20161104_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='12345678', max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\S){4,}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='12345678', max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\S){4,}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='12345678', max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\S){4,}$')]),
        ),
    ]
