# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_auto_20161109_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='receive_stu',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
