# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_auto_20161109_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='readed',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
