# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20161109_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
